services:
  be-stamping-new:
    build:
      context: .
      dockerfile: Dockerfile
    image: riankurniawan/be-stamping:latest
    container_name: be-stamping-new
    restart: always
    ports:
      - 5003:5003
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    networks:
      - iot-stamping-network

networks:
  iot-stamping-network:
    driver: bridge
